spring:
  application:
    name: consumer-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: 'true'
          max-attempts: '3'
          initial-interval: 5s
          multiplier: '2'

server:
  port: 8083